#!/bin/bash

# This script is used to collect server statistics
# and diplay them in a user-friendly format.
#
# The script is able to be run on any Linux server
# and it gives the following stats:
# 1. total CPU usage
# 2. total memory usage (Free vs Used including percentage)
# 3. total disk usage (Free vs Used including percentage)
# 4. top 5 processes by CPU usage
# 5. top 5 processes by memory usage
#
# Partly generated by Microsoft Copilot.


# Function to get CPU usage
get_cpu_usage() {
    echo "CPU Usage:"
    # Get the total CPU usage
    cpu_usage=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1}')
    echo "Total CPU Usage: $cpu_usage%"
}

# Function to get memory usage
get_memory_usage() {
    echo "Memory Usage:"
    # Get the total memory usage
    mem_info=$(free -m)
    total_mem=$(echo "$mem_info" | awk 'NR==2{print $2}')
    used_mem=$(echo "$mem_info" | awk 'NR==2{print $3}')
    free_mem=$(echo "$mem_info" | awk 'NR==2{print $4}')
    mem_percentage=$(echo "scale=2; $used_mem/$total_mem*100" | bc)
    echo "Total Memory: $total_mem MB"
    echo "Used Memory: $used_mem MB ($mem_percentage%)"
    echo "Free Memory: $free_mem MB"
}

# Function to get disk usage
get_disk_usage() {
    echo "Disk Usage:"
    # Get the total disk usage
    disk_info=$(df -h)
    total_disk=$(echo "$disk_info" | grep '/$' | awk '{print $2}')
    used_disk=$(echo "$disk_info" | grep '/$' | awk '{print $3}')
    free_disk=$(echo "$disk_info" | grep '/$' | awk '{print $4}')
    disk_percentage=$(echo "$disk_info" | grep '/$' | awk '{print $5}')
    echo "Total Disk: $total_disk"
    echo "Used Disk: $used_disk ($disk_percentage)"
    echo "Free Disk: $free_disk"
}

# Function to get top 5 processes by CPU usage.
get_top_cpu_processes() {
    top_processes=$(ps -eo comm --sort=-%cpu | head -n 6 \
    | awk 'NR>1')
    processes_csv=$(echo "$top_processes" | paste -sd', ' -)

    echo "Top processes by CPU usage: $processes_csv"
}

# Function to get top 5 processes by memory usage
get_top_memory_processes() {
    echo "Top 5 Processes by Memory Usage:"
    # Get the top 5 processes by memory usage
    ps -eo pid,comm,%mem --sort=-%mem | head -n 6
}

# Main function to call all other functions
main() {
    get_cpu_usage
    echo
    get_memory_usage
    echo
    get_disk_usage
    echo
    get_top_cpu_processes
    echo
    get_top_memory_processes
}

# Call the main function
main