#!/bin/bash

# This script is used to collect server statistics
# and diplay them in a user-friendly format.
#
# The script is able to be run on any Linux server
# and it gives the following stats:
# 1. total CPU usage
# 2. total memory usage (Free vs Used including percentage)
# 3. total disk usage (Free vs Used including percentage)
# 4. top 5 processes by CPU usage
# 5. top 5 processes by memory usage
#
# Partly generated by Microsoft Copilot.


# Function to get CPU usage
get_cpu_usage() {
    cpu_usage=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{printf "%s", 100 - $1}')
    echo "CPU usage: $cpu_usage%"
}

# Function to get memory usage
get_memory_usage() {
    mem_info=$(free -m)
    total_mem=$(echo "$mem_info" | awk 'NR==2{print $2}')
    used_mem=$(echo "$mem_info" | awk 'NR==2{print $3}')
    free_mem=$(echo "$mem_info" | awk 'NR==2{print $4}')
    mem_percentage=$(echo "scale=2; $used_mem/$total_mem*100" | bc)
    echo "memory usage: $used_mem/$total_mem MB ($mem_percentage%)"
}

# Function to get disk usage
get_disk_usage() {
    echo "Disk Usage:"
    # Get the total disk usage
    disk_info=$(df -h)
    total_disk=$(echo "$disk_info" | grep '/$' | awk '{print $2}')
    used_disk=$(echo "$disk_info" | grep '/$' | awk '{print $3}')
    free_disk=$(echo "$disk_info" | grep '/$' | awk '{print $4}')
    disk_percentage=$(echo "$disk_info" | grep '/$' | awk '{print $5}')
    echo "Total Disk: $total_disk"
    echo "Used Disk: $used_disk ($disk_percentage)"
    echo "Free Disk: $free_disk"
}

# Function to get top 5 processes by a given resource
# usage.
get_top_processes() {
    criterion_symbol=$1
    criterion_name=$2
    top_processes=$(ps -eo comm --sort=-"$criterion_symbol" | head -n 6 \
    | awk 'NR>1')
    processes_csv=$(echo "$top_processes" | paste -sd', ' -)

    echo "$criterion_name heaviest: $processes_csv"
}

# Main function to call all other functions
main() {
    get_cpu_usage
    get_memory_usage
    echo
    get_disk_usage
    echo
    get_top_processes "%cpu" CPU
    get_top_processes "%mem" memory
}

# Call the main function
main
