#!/bin/bash

# This script is used to collect server statistics
# and diplay them in a user-friendly format.
#
# The script is able to be run on any Linux server
# and it gives the following stats:
# 1. total CPU usage
# 2. total memory usage (Free vs Used including percentage)
# 3. total disk usage (Free vs Used including percentage)
# 4. top 5 processes by CPU usage
# 5. top 5 processes by memory usage
#
# Partly generated by Microsoft Copilot.


# Function to print top 5 processes by CPU and memory
# usage.
print_heaviest_processes() {
	printf "%-10s %-10s\n" "by CPU" "by memory"

	top_cpu=($(ps -eo comm --sort=-%cpu | awk 'NR>=2 && NR<=7'))
	top_memory=($(ps -eo comm --sort=-%mem | awk 'NR>=2 && NR<=7'))
	
	for ((i=0; i < 5; i++)); do
		printf "%-10.10s %-10.10s\n" ${top_cpu[i]} ${top_memory[i]}
	done
}

# Main function to call all other functions
main() {
	cpu_usage=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{printf "%s", 100 - $1}')

	mem_info=$(free -m)

	mem_total=$(echo "$mem_info" | awk 'NR==2{print $2}')
	mem_used=$(echo "$mem_info" | awk 'NR==2{print $3}')
	mem_free=$(echo "$mem_info" | awk 'NR==2{print $4}')
	mem_percentage=$(echo "scale=2; $mem_used/$mem_total*100" | bc)


	disk_info=$(df -BG -l | grep '/$')

	disk_total=$(echo $disk_info | awk '{print $2}')
	disk_total=${disk_total%?}
	disk_used=$(echo $disk_info | awk '{print $3}')
	disk_used=${disk_used%?}
	disk_free=$(echo $disk_info | awk '{print $4}')
	disk_free=${disk_free%?}
	disk_percentage=$(echo $disk_info | awk '{print $5}')

	echo "Resource Usage"
	echo
	printf "\t%%\tused\tfree\ttotal\n"
	printf "CPU\t%s\n" $cpu_usage
	printf "memory\t%s\t%s\t%s\t%s\n" \
		$mem_percentage $mem_used $mem_free $mem_total	
	printf "disk\t%s\t%s\t%s\t%s\n" \
	       	$disk_percentage $disk_used $disk_free $disk_total	

	echo
	echo "Heaviest Processes"
	echo
	print_heaviest_processes
}

# Call the main function
main
